default: run-all

clean: 
	@echo "cleaning up"
	@rm -f bin/*

build-all:
	just build 01
	just build 02

run-all: clean build-all 
	bin/01
	bin/02

build day: 
	go build -o bin/{{day}} {{day}}/main.go

run day: clean
	just build {{day}}
	bin/{{day}}


# vim: set ft=make :
